import React, { useState } from 'react';
import { PageHeader, Card, Badge, Button, Input } from '@/components';
import { CheckCircle2, XCircle, Search, Award, ShieldCheck } from 'lucide-react';
import {
  mockCompanyPPOs,
  mockFacultyStudents,
  mockCompanyInternships,
  setMockCompanyPPOs,
  type CompanyPPOData,
} from '@/features/faculty/mockData';

export const AdminPPOs: React.FC = () => {
  const [ppos, setPpos] = useState<CompanyPPOData[]>(mockCompanyPPOs);
  const [searchTerm, setSearchTerm] = useState('');

  const fullPpoList = ppos.map((ppo) => {
    const student = mockFacultyStudents.find((s) => s.id === ppo.internId);
    const internship = mockCompanyInternships.find((i) => i.id === ppo.internshipId);
    return {
      ...ppo,
      studentName: student?.studentName || 'Sarah Smith',
      department: student?.department || 'CSE',
      role: ppo.jobRole || internship?.title || 'Junior Developer',
      ctc: ppo.ctc || '₹12,00,000 LPA',
      company: internship?.domain || 'TechCorp Solutions',
    };
  });

  const filteredPpos = fullPpoList.filter(
    (p) =>
      p.studentName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.role.toLowerCase().includes(searchTerm.toLowerCase()) ||
      p.company.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleTpoApprove = (ppoId: string) => {
    const updated = ppos.map((p) => (p.id === ppoId ? { ...p, status: 'Offered' as const } : p));
    setPpos(updated);
    setMockCompanyPPOs(updated);
  };

  const handleTpoReject = (ppoId: string) => {
    const updated = ppos.map((p) => (p.id === ppoId ? { ...p, status: 'Not Converted' as const } : p));
    setPpos(updated);
    setMockCompanyPPOs(updated);
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="PPO Verification & Approvals"
        description="Review and verify Pre-Placement Offers generated by industry partners before faculty and student release."
      />

      <Card className="p-6 bg-white border border-slate-200">
        <div className="mb-6 relative max-w-md">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
          <Input
            placeholder="Search by student name, role, or company..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9"
          />
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 text-slate-500 bg-slate-50">
                <th className="p-3 font-semibold">Student Name</th>
                <th className="p-3 font-semibold">Department</th>
                <th className="p-3 font-semibold">Offer Role & CTC</th>
                <th className="p-3 font-semibold">Company</th>
                <th className="p-3 font-semibold">Status</th>
                <th className="p-3 font-semibold text-right">TPO Verification</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredPpos.map((ppo) => (
                <tr key={ppo.id} className="hover:bg-slate-50/50">
                  <td className="p-3 font-bold text-slate-800 flex items-center gap-2">
                    <Award className="w-4 h-4 text-indigo-600 shrink-0" />
                    <span>{ppo.studentName}</span>
                  </td>
                  <td className="p-3">
                    <Badge variant="sky">{ppo.department}</Badge>
                  </td>
                  <td className="p-3 text-slate-700">
                    <span className="font-semibold block">{ppo.role}</span>
                    <span className="text-[10px] text-emerald-600 font-bold">{ppo.ctc}</span>
                  </td>
                  <td className="p-3 text-slate-600">{ppo.company}</td>
                  <td className="p-3">
                    <Badge variant={ppo.status === 'Offered' ? 'emerald' : ppo.status === 'Not Converted' ? 'rose' : 'amber'}>
                      <ShieldCheck className="w-3 h-3 mr-1 inline" /> {ppo.status}
                    </Badge>
                  </td>
                  <td className="p-3 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      {ppo.status !== 'Offered' && (
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-emerald-600 hover:bg-emerald-50 text-[11px] p-1.5"
                          onClick={() => handleTpoApprove(ppo.id)}
                        >
                          <CheckCircle2 className="w-3.5 h-3.5 mr-1" /> Approve PPO
                        </Button>
                      )}
                      {ppo.status !== 'Not Converted' && (
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-rose-600 hover:bg-rose-50 text-[11px] p-1.5"
                          onClick={() => handleTpoReject(ppo.id)}
                        >
                          <XCircle className="w-3.5 h-3.5 mr-1" /> Reject PPO
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};
